spring.profiles.active=local
spring.application.name=spring-backend
cors.allowed-origins=http://localhost:5173,http://192.168.1.6:5173
server.servlet.context-path=/api
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
logging.level.org.springframework.security=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true